
package wayzim.cn.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherWSSoap", targetNamespace = "http://service.cn.wayzim")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherWSSoap {


    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://service.cn.wayzim", className = "wayzim.cn.service.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://service.cn.wayzim", className = "wayzim.cn.service.GetWeatherResponse")
    @Action(input = "http://service.cn.wayzim/WeatherWSSoap/getWeatherRequest", output = "http://service.cn.wayzim/WeatherWSSoap/getWeatherResponse")
    public String getWeather(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

}
